### ISSUE TITLE
session.get_bookmarks() does not handle deleted works

### ISSUE THREAD

**Issue by Spaze47** [ArmindoFlores/ao3_api#41]
While using the `session.get_bookmarks()` method, the API throws the following error:
```
Traceback (most recent call last):
  File "c:\Users\spaze\scriptdev\projects\ao3\bookmark-export\main.py", line 14, in <module>
    bookmarks = session.get_bookmarks()
  File "C:\Users\spaze\AppData\Roaming\Python\Python39\site-packages\AO3\session.py", line 446, in get_bookmarks
    self._load_bookmarks(page=page+1)
  File "C:\Users\spaze\AppData\Roaming\Python\Python39\site-packages\AO3\threadable.py", line 13, in new
    return func(*args, **kwargs)
  File "C:\Users\spaze\AppData\Roaming\Python\Python39\site-packages\AO3\session.py", line 478, in _load_bookmarks
    new = Work(workid, load=False)
UnboundLocalError: local variable 'workid' referenced before assignment
```

I am unable to say with perfect confidence that bookmarked deleted works are the cause of my problem. However, inserting a print statement in `session._load_bookmarks()` right after `new = Work(workid, load=False)` shows that quite a few of my bookmarks _are_ loaded successfully before the error is thrown. And obviously, I do have a few bookmarks in my list that are deleted and could be the cause.

Sorry if this isn't that helpful, I've never actually opened an issue myself before.

**Comment by ArmindoFlores** [comment]
I will definitely look into it!

**Comment by ArmindoFlores** [comment]
Should be fine now. Let me know if it still errors out!

**Comment by Spaze47** [comment]
No longer throws the error – now it's just one from a mistake with my own poor code. Thanks for the fix!
