### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by MarcoDotIO** [ArmindoFlores/ao3_api#6]
I am getting the following error while using ao3_api on Python 2.7.17:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rachnera/.local/lib/python2.7/site-packages/AO3/__init__.py", line 1, in <module>
    from . import extra, utils
  File "/home/rachnera/.local/lib/python2.7/site-packages/AO3/extra.py", line 23
    print(f"Downloading from {url}")
                                  ^
SyntaxError: invalid syntax
`

I'm also getting this error with Python 3.7.5:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rachnera/.local/lib/python3.7/site-packages/AO3/__init__.py", line 2, in <module>
    from .comments import Comment
  File "/home/rachnera/.local/lib/python3.7/site-packages/AO3/comments.py", line 5, in <module>
    from .users import User
  File "/home/rachnera/.local/lib/python3.7/site-packages/AO3/users.py", line 2, in <module>
    from functools import cached_property
ImportError: cannot import name 'cached_property' from 'functools' (/usr/lib/python3.7/functools.py)`

**Comment by Wrench-wench** [comment]
#3 In another issue it's noted that the ao3_api requires Python3.8.

See my comment at the end for a rough guide on how to upgrade Python to the correct version.
