### ISSUE TITLE
Can't return search total results if > 1000 due to ',' in string

### ISSUE THREAD

**Issue by Tophattingson** [ArmindoFlores/ao3_api#82]
```
Traceback (most recent call last):
  File "C:\Users\achar\Documents\Python\ao3 relationship graph\genshin v2.py", line 107, in <module>
    results = worksforship(relationship)
  File "C:\Users\achar\Documents\Python\ao3 relationship graph\genshin v2.py", line 80, in worksforship
    search.update()
  File "C:\Users\achar\AppData\Local\Programs\Python\Python38\lib\site-packages\AO3\threadable.py", line 13, in new
    return func(*args, **kwargs)
  File "C:\Users\achar\AppData\Local\Programs\Python\Python38\lib\site-packages\AO3\search.py", line 112, in update
    self.total_results = int(maindiv.find("h3", {"class": "heading"}).getText().strip().split(" ")[0])
ValueError: invalid literal for int() with base 10: '4,076'
```

Solution is to add .replace(',','') to self.total_results or equivalent

**Comment by EtchJetty** [comment]
Seconding this problem.

**Comment by nvl-github** [comment]
Thirding this problem! Cannot perform int() on a string with a comma character in it. We see the issue currently on the documented example of the Search class .update() method:
```
 search = AO3.Search(any_field="Clarke Lexa", word_count=AO3.utils.Constraint(5000, 15000))
>>> search.update()
Traceback (most recent call last):
  File "<pyshell#3>", line 1, in <module>
    search.update()
  File "C:\Users\nicol\AppData\Local\Programs\Python\Python39-32\lib\site-packages\AO3\threadable.py", line 13, in new
    return func(*args, **kwargs)
  File "C:\Users\nicol\AppData\Local\Programs\Python\Python39-32\lib\site-packages\AO3\search.py", line 112, in update
    self.total_results = int(maindiv.find("h3", {"class": "heading"}).getText().strip().split(" ")[0])
ValueError: invalid literal for int() with base 10: '3,364'
```

**Comment by nvl-github** [comment]
I raised a pull request for this, I just don't know how to assign anyone to review and approve it. @ArmindoFlores many apologies for my newbness. [https://github.com/ArmindoFlores/ao3_api/pull/93]

**Comment by CatinoRosalba** [comment]
Hi @nvl-github and @ArmindoFlores, in my country the delimiter of thousands is a dot. When I run a search, like the example in the github documentation, I keep getting that error: "ValueError: invalid literal for int() with base 10: '4,076'". 
Any suggestions?
